# Management and Prometheus Configuration
management:
  prometheus:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      show-details: never
    shutdown:
      access: none

# Logging Configuration
logging:
  level:
    root: info
    org:
      springframework: warn
      boot: error
    data:
      redis: debug
  pattern:
    console: "%n%d{HH:mm:ss} | %highlight(%-5level) | %cyan(%logger{30}) | %msg"

# SpringDoc (Swagger) Configuration
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    enabled: ${SWAGGER_ENABLE:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLE:false}
    path: ${SWAGGER_URL:/docs}

# Spring General Configurations
spring:
  output:
    ansi:
      enabled: always
  aop:
    auto: true
  banner:
    location: classpath:banner.txt
  main:
    banner-mode: console

# Application Info
info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
  java:
    version: ${project.java.version}
